version: '3.7'

services:
  ego-searcher:
    image: ciffelia/ego-searcher
    build: .
    restart: always
    init: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./config.js:/home/egosearcher/config.js
